- name: fix ca-certs
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: download cURL/mozilla cert bundle insecurely
      get_url:
        url: https://curl.se/ca/cacert.pem
        dest: /usr/share/ca-certificates/local/ca-bundle.crt
        validate_certs: no
      notify: update certs

  handlers:
    - name: update certs
      shell:
        command: update-ca-certificates
