- import_playbook: ./ros2_repos.yml

- name: install colcon
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: install (unlisted!) dependencies of ros
      apt:
        name:
          - libtinyxml2-dev
        state: present

    - name: install colcon & rosdep
      apt:
        name:
        - python3-colcon-common-extensions
        - python3-rosdep
        install_recommends: yes
        state: present

    - name: initialise rosdep
      shell: rosdep init
      args:
        creates: /etc/ros/rosdep/sources.list.d/20-default.list
      notify: update rosdep repos

  handlers:
    - name: update rosdep repos
      shell: rosdep update
