- name: pipuck-specific setup
  import_playbook: ./pi_gen_rip.yml

- name: our custom scripts
  import_playbook: ./our_scripts.yml

- name: install pip packages globally
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: packages
      pip:
        name:
          # https://pypi.org/project/luma.oled/
          - luma.oled
        state: present

- name: install ros2
  hosts: all
  gather_facts: no

  vars:
    ros2_archive: "../ros2-foxy-20210902-linux-focal-arm64.tar.bz2"

  roles:
    - role: laura7089.ros2
      ros2_source: local
      ros2_local_archive: "{{ ros2_archive }}"
      rosdep_install: no
