- name: pipuck-specific setup
  import_playbook: ./pi_gen_rip.yml

- name: our custom scripts
  import_playbook: ./our_scripts.yml

- name: install pip packages globally
  hosts: all
  become: yes

  tasks:
    - name: packages
      pip:
        name:
          # https://pypi.org/project/luma.oled/
          - luma.oled
        state: present

- name: install ros2
  hosts: all
  roles:
    - { role: laura7089.ros2 }
