- hosts: all
  become: yes

  tasks:
    - name: copy script to machine
      copy:
        src: "../scripts/hostname_set.sh"
        dest: "/usr/bin/hostname_set"
        mode: 0755
    - name: link into startup
      file:
        src: "/usr/bin/hostname_set"
        dest: "/etc/init.d/hostname_set"
        state: link
    - name: run script
      cmd: "/usr/bin/hostname_set"
