# vi: set ft=yaml.ansible:
- name: apt config
  hosts: all
  become: yes
  gather_facts: no

  vars:
    pipuck_gen: "../tools/pi-gen-yrl/stage2+pi-puck/00-configure-apt"

  tasks:
    - name: add pi-puck apt repo key
      apt_key:
        url: "https://raw.githubusercontent.com/yorkrobotlab/pi-gen/376f464c2ab6fd43aa5939f1db86150c5f4e36ae/stage2%2Bpi-puck/00-configure-apt/files/pi-puck.gpg.key"
        state: present

    - name: add pi-puck apt repo
      apt_repo:
        repo: "deb http://www.cs.york.ac.uk/pi-puck/debian/ buster main"
        state: present

    - name: apt dist upgrade
      apt:
        upgrade: dist
        update_cache: yes

- name: pi-puck core
  hosts: all
  become: yes
  gather_facts: no

  vars:
    pipuck_gen: "../tools/pi-gen-yrl/stage2+pi-puck/01-pi-puck-core"

  tasks:
    - name: pi puck core package
      apt:
        name: pi-puck-core
        state: present

    - name: boot config additions
      blockinfile:
        path: /boot/config.txt
        block: |
          [all]
          include pi-puck-config.txt
        marker: ""

    - name: i2c config
      copy:
        content: i2c-dev
        dest: "/etc/modules-load.d/i2c-dev.conf"
        mode: 0644

- name: boot files
  hosts: all
  become: yes
  gather_facts: no

  vars:
    pipuck_gen: "../tools/pi-gen-yrl/stage2+pi-puck/02-pi-puck-boot-files"

  tasks:
    - name: boot files
      copy:
        src: "{{ item }}"
        dest: "/boot/"
      with_items:
        - "{{ pipuck_gen }}/files/e-puck_id"
        - "{{ pipuck_gen }}/files/pi-puck_id"
        - "{{ pipuck_gen }}/files/hostname"
        - "{{ pipuck_gen }}/files/wpa_supplicant.conf"

- name: useful packages
  hosts: all
  become: yes
  gather_facts: no

  vars:
    pipuck_gen: "../tools/pi-gen-yrl/stage2+pi-puck/03-useful-packages"

  tasks:
    - name: install packages
      apt:
        name: "{{ item.replace('\n', ' ') }}"
        state: present
      with_file: ["{{ pipuck_gen }}/00-packages"]
