- name: "apt config"
  hosts: all
  become: yes

  vars:
    pipuck_gen: "../tools/pi-gen-yrl/stage2+pi-puck"

  tasks:
    - name: add pi-puck apt repo key
      apt_key:
        data: "{{ item }}"
        state: present
      with_file:
        - "{{ pipuck_gen }}/00-configure-apt/files/pi-puck.gpg.key"

    - name: add pi-puck apt repo
      apt_repo:
        repo: "{{ item }}"
        state: present
      with_file:
        - "{{ pipuck_gen }}/00-configure-apt/files/pi-puck.list"

    - name: apt dist upgrade
      apt:
        upgrade: dist
        update_cache: yes
