- import_playbook: ./colcon_rosdep.yml

- name: install rcl
  hosts: all
  gather_facts: no

  tasks:
    - name: get rcl source
      git:
        repo: https://github.com/ros2/rcl.git
        dest: ~/rclpy_ws/src/rcl
        version: release-latest

- name: install rclpy
  hosts: all
  gather_facts: no

  tasks:
    - name: install apt deps
      become: yes
      apt:
        name:
          - python3-sphinx
          - python3-pip
          - libssl-dev
        state: present

    - name: install pip deps
      become: yes
      pip:
        name: sphinx_autodoc_typehints
        state: present

    - name: get rclpy source
      git:
        repo: https://github.com/ros2/rclpy
        dest: ~/rclpy_ws/src/rclpy
        version: release-latest

    - name: install deps with rosdep
      shell: |
        source /opt/ros/foxy/setup.bash && \
        rosdep install --from-paths src --ignore-src --rosdistro foxy
      args:
        chdir: ~/rclpy_ws
        executable: /bin/bash

    - name: run colcon build
      shell: |
        source /opt/ros/foxy/setup.bash && \
        colcon build
      args:
        chdir: ~/rclpy_ws
        executable: /bin/bash
