- import_playbook: ./cacerts.yml

- name: enable ros2 apt repos
  hosts: all
  become: yes

  tasks:
    - name: enable ros2 gpg key
      apt_key:
        url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc
        state: present

    - name: enable ros2 repo
      lineinfile:
        line: "deb [arch=amd64,arm64] http://repo.ros2.org/ubuntu/main {{ ansible_distribution_release }} main"
        path: /etc/apt/sources.list.d/ros2-latest.list
        create: yes
        state: present
